services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm start
    environment:
      - RESOURCE_CONFIG=${RESOURCE_CONFIG}
      - OPERATION_CONFIG=${OPERATION_CONFIG}
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${PORT}:3000'
