---
name: build app

on: [push, pull_request]

jobs:
  build-test:
    strategy:
      matrix:
        node-version:
          - 18
          - 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node-${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and build the code
        run: npm install
      - name: Verify styling
        id: style_verify
        run: npm run format-dryrun
      - name: Verify styling failure msg
        if: steps.style_verify.outcome == 'failure'
        run: echo "Please run 'npm run format' before commiting the code!"
      - name: Run build
        run: npm run build
